# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38a83a80ce9c8b33537a650ac807d05910d3a074a1bf8ad30a689808c30bdac4a7e0203e3156bb64eb85353363ea86e71f07cfe5951442b421b818db0a5bcc6

test:
  secret_key_base: fdedb86bca30a4ed53891fb57dc1c6ee70e1f44e50908b61b299ca2b8511a103394a9bf15573e8e27843c3253ae7a842a52e03ad0273fe289d7753f5621f8d32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
